#include <hpu/arithmetic.h>
#include <hpu/cache.h>
#include <hpu/csr.h>
#include <hpu/dma.h>
#include <hpu/fixture.h>
#include <hpu/layout.h>
#include <hpu/sync.h>

/*
 * Purpose: close a complete 4096-coefficient HPU compute path:
 *
 *   load modulus/A/B -> select modulus -> PADD -> DSTORE -> PSYNC -> compare
 *
 * Both input polynomials are one RNS limb and share q=65537.  The C oracle
 * computes (A[i] + B[i]) mod q independently for every output coefficient.
 */
int main(void) {
    volatile uint32_t *modulus_record = hpu_line(HPU_LINE_MOD);
    const uint64_t barrett_mu = UINT64_MAX / HPU_MODULUS;
    uint32_t status = 0U;
    unsigned timeout;
    unsigned i;

    if (hpu_fixture_validate_embedded() != 0) return 1;

    /* Program and read back all four HPU memory-window shadow CSRs. */
    hpu_csr_write32(HPU_CSR_FAULT_ADDR, HPU_FAULT_VALID);
    hpu_csr_write32(HPU_CSR_IRQ_ADDR, HPU_IRQ_LEVEL);
    hpu_csr_write32(HPU_CSR_IRQ_ADDR, 0U);
    hpu_csr_write32(HPU_CSR_BASE_LO_ADDR, (uint32_t)HPU_MEM_BASE);
    hpu_csr_write32(HPU_CSR_BASE_HI_ADDR,
                    (uint32_t)(HPU_MEM_BASE >> 32U));
    hpu_csr_write32(HPU_CSR_SIZE_LO_ADDR, HPU_WINDOW_LINES);
    hpu_csr_write32(HPU_CSR_SIZE_HI_ADDR, 0U);

    if (hpu_csr_read32(HPU_CSR_BASE_LO_ADDR) != (uint32_t)HPU_MEM_BASE)
        return 1;
    if (hpu_csr_read32(HPU_CSR_BASE_HI_ADDR) !=
        (uint32_t)(HPU_MEM_BASE >> 32U))
        return 1;
    if (hpu_csr_read32(HPU_CSR_SIZE_LO_ADDR) != HPU_WINDOW_LINES)
        return 1;
    if (hpu_csr_read32(HPU_CSR_SIZE_HI_ADDR) != 0U) return 1;

    hpu_csr_write32(HPU_CSR_COMMIT_ADDR, HPU_COMMIT_REQUEST);
    for (timeout = 0U; timeout < HPU_TIMEOUT; ++timeout) {
        status = hpu_csr_read32(HPU_CSR_STATUS_ADDR);
        if ((status & HPU_STATUS_FAULT_VALID) != 0U) return 1;
        if ((status & HPU_STATUS_WINDOW_VALID) != 0U) break;
    }
    if (timeout == HPU_TIMEOUT) return 1;
    if ((status & HPU_STATUS_BUSY) != 0U) return 1;
    if ((hpu_csr_read32(HPU_CSR_FAULT_ADDR) & HPU_FAULT_VALID) != 0U)
        return 1;
    if ((hpu_csr_read32(HPU_CSR_IRQ_ADDR) & HPU_IRQ_LEVEL) != 0U)
        return 1;

    /*
     * One 128-bit modulus record occupies words 0..3 of line 0:
     *   word0 = q32
     *   word1 = Barrett mu[31:0]
     *   word2 = Barrett mu[47:32] (upper 16 bits remain zero)
     *   word3 = reserved zero
     */
    for (i = 0U; i < HPU_WORDS_PER_LINE; ++i) modulus_record[i] = 0U;
    modulus_record[0] = HPU_MODULUS;
    modulus_record[1] = (uint32_t)barrett_mu;
    modulus_record[2] = (uint32_t)(barrett_mu >> 32U);
    modulus_record[3] = 0U;
    hpu_fence();
    hpu_cache_clean((uintptr_t)modulus_record, HPU_LINE_BYTES);

    /* Copy the two independent ELF vectors and poison the whole output. */
    hpu_fixture_copy_to_ddr(HPU_LINE_SRC_A, hpu_rns_input_a);
    hpu_fixture_copy_to_ddr(HPU_LINE_SRC_B, hpu_rns_input_b);
    hpu_fixture_poison_output();

    /*
     * Instruction sequence generated by the pinned inline-asm encoding:
     *   dload mod-context -> p4, dload A -> p0, dload B -> p1,
     *   pmodld 0, padd p2,p0,p1, dstore p2 release, terminal psync.
     */
    hpu_dload_mod_p4(HPU_LINE_MOD, 1U);
    hpu_dload_p0(HPU_LINE_SRC_A, HPU_RNS_LINES);
    hpu_dload_p1(HPU_LINE_SRC_B, HPU_RNS_LINES);
    hpu_pmodld_0();
    hpu_padd_p2_p0_p1();
    hpu_dstore_p2_release(HPU_LINE_OUTPUT, HPU_RNS_LINES);
    hpu_psync();

    for (timeout = 0U; timeout < HPU_TIMEOUT; ++timeout) {
        status = hpu_csr_read32(HPU_CSR_STATUS_ADDR);
        if ((status & HPU_STATUS_FAULT_VALID) != 0U) return 1;
        if ((hpu_csr_read32(HPU_CSR_IRQ_ADDR) & HPU_IRQ_LEVEL) != 0U)
            break;
    }
    if (timeout == HPU_TIMEOUT) return 1;
    if ((status & HPU_STATUS_BUSY) != 0U) return 1;

    hpu_csr_write32(HPU_CSR_IRQ_ADDR, HPU_IRQ_LEVEL);
    for (timeout = 0U; timeout < HPU_TIMEOUT / 16U; ++timeout) {
        if ((hpu_csr_read32(HPU_CSR_IRQ_ADDR) & HPU_IRQ_LEVEL) == 0U)
            break;
    }
    hpu_csr_write32(HPU_CSR_IRQ_ADDR, 0U);
    if (timeout == HPU_TIMEOUT / 16U) return 1;

    /* Compare all 4096 HPU results with the independent C modular-add oracle. */
    if (hpu_fixture_check_padd() != 0) return 1;
    return 0;
}
