#include "hpu_fhe.h"

#include "../hpu_inline_asm.h"
#include "../third_party/inline-asm/outputs/ciphertext_multiply/ciphertext_multiply.h"
#include "../third_party/inline-asm/outputs/keyswitch/keyswitch.h"
#include "../third_party/inline-asm/outputs/relinearization/relinearization.h"

#include <stddef.h>
#include <stdint.h>

#if defined(HPU_IT_NEXUS_AM)
#include <am.h>
#include <klib.h>
#else
#include <stdio.h>
#include <time.h>
#endif

#if defined(__riscv) && defined(HPU_IT_STANDALONE_HTIF) && \
    HPU_IT_STANDALONE_HTIF
/* Standalone Spike has no Nanhu UARTLite model; keep HTIF runs nonblocking. */
static int hpu_fhe_silent_printf(const char *format, ...) {
    (void)format;
    return 0;
}
#undef printf
#define printf hpu_fhe_silent_printf
#endif

#ifndef HPU_IT_MEM_BASE
#define HPU_IT_MEM_BASE 0x87000000UL
#endif

#ifndef HPU_IT_MEM_LINES
#define HPU_IT_MEM_LINES 19201U
#endif

#ifndef HPU_IT_ENABLE_MMIO
#if defined(__riscv)
#define HPU_IT_ENABLE_MMIO 1
#else
#define HPU_IT_ENABLE_MMIO 0
#endif
#endif

#ifndef HPU_IT_WAIT_IRQ
#define HPU_IT_WAIT_IRQ HPU_IT_ENABLE_MMIO
#endif

#ifndef HPU_IT_USE_GENERATED_FHE
#define HPU_IT_USE_GENERATED_FHE 0
#endif

#ifndef HPU_IT_VECTOR_ROOT
#error "HPU_IT_VECTOR_ROOT must name the IT-SCPU-TestCases source directory"
#endif

#define FHE_LINE_BYTES             256U
#define FHE_WORDS_PER_LINE         64U
#define FHE_N                      4096U
#define FHE_POLY_LINES             64U
#define FHE_Q_COUNT                4U
#define FHE_P_COUNT                3U
#define FHE_BASIS_COUNT            7U
#define FHE_DIGITS                 2U
#define FHE_MASTER_LINES           16961U
#define FHE_BROADCAST_COUNT        31U
#define FHE_BROADCAST_STRIDE       FHE_POLY_LINES
#define FHE_BROADCAST_END          \
    (FHE_MASTER_LINES + FHE_BROADCAST_COUNT * FHE_BROADCAST_STRIDE)
#define FHE_GUARD_LINES            64U
#define FHE_SCRATCH_LINES          (FHE_P_COUNT * FHE_POLY_LINES)
#define FHE_GUARD_BEGIN            (FHE_BROADCAST_END + FHE_SCRATCH_LINES)
#define FHE_REQUIRED_LINES         (FHE_GUARD_BEGIN + FHE_GUARD_LINES)
#define FHE_GUARD_WORD             0xa5a55a5aU
#define FHE_POISON_WORD            0xd15ea5edU
#define FHE_IRQ_TIMEOUT            200000000U

#if FHE_REQUIRED_LINES != 19201U
#error "FHE delivery profile must end with the explicit tail guard"
#endif

#define FHE_CSR_BASE               0x08000000UL
#define FHE_CSR_BASE_LO            0x00U
#define FHE_CSR_BASE_HI            0x04U
#define FHE_CSR_SIZE_LO            0x08U
#define FHE_CSR_SIZE_HI            0x0cU
#define FHE_CSR_COMMIT             0x10U
#define FHE_CSR_STATUS             0x14U
#define FHE_CSR_FAULT              0x18U
#define FHE_CSR_IRQ                0x1cU
#define FHE_STATUS_WINDOW_VALID    (1U << 0)

/* Frozen master line map generated by cuihu2/inline-asm. */
#define FHE_LINE_CTA               0U
#define FHE_LINE_CTB               512U
#define FHE_LINE_SCRATCH           FHE_BROADCAST_END
#define FHE_LINE_RLK               1408U
#define FHE_LINE_INPUT_NTT         3200U
#define FHE_LINE_TENSOR_NTT        4224U
#define FHE_LINE_TENSOR_COEFF      4992U
#define FHE_LINE_MODUP_COEFF       5760U
#define FHE_LINE_MODUP_NTT         6656U
#define FHE_LINE_KS_ACC_NTT        7552U
#define FHE_LINE_KS_COEFF          8448U
#define FHE_LINE_KS_MODDOWN        9344U
#define FHE_LINE_CIPHER_OUT        9856U
#define FHE_LINE_MOD_CTX           10688U
#define FHE_LINE_TWIDDLE           10689U
#define FHE_TWIDDLE_BASIS_STRIDE   896U
#define FHE_TWIDDLE_NTT_STAGE      64U
#define FHE_TWIDDLE_INTT_STAGE     448U
#define FHE_TWIDDLE_POST           832U
#define FHE_STAGE_LINES            32U
#define FHE_STAGE_COUNT            12U

#if defined(__GNUC__)
#define FHE_MAYBE_UNUSED __attribute__((unused))
#else
#define FHE_MAYBE_UNUSED
#endif

#define FHE_MASTER_IMAGE_PATH                                      \
    "/third_party/inline-asm/outputs/ciphertext_multiply/test_data" \
    "/hardware/hpu_mem_image.u32.bin"

__asm__(
    ".pushsection .rodata.hpu_fhe_master,\"a\",@progbits\n"
    ".balign 256\n"
    ".global hpu_fhe_master_begin\n"
    ".type hpu_fhe_master_begin,@object\n"
    "hpu_fhe_master_begin:\n"
    ".incbin \"" HPU_IT_VECTOR_ROOT FHE_MASTER_IMAGE_PATH "\"\n"
    ".global hpu_fhe_master_end\n"
    "hpu_fhe_master_end:\n"
    ".size hpu_fhe_master_begin,hpu_fhe_master_end-hpu_fhe_master_begin\n"
    ".popsection\n");

extern const uint8_t hpu_fhe_master_begin[];
extern const uint8_t hpu_fhe_master_end[];

/* Q0..Q3 followed by P0..P2, exactly as constants/mod_ctx.u32.bin. */
static const uint32_t fhe_moduli[FHE_BASIS_COUNT] = {
    50061313U, 50077697U, 50307073U, 50552833U,
    90062849U, 90095617U, 90218497U,
};

/*
 * Full-polynomial broadcast constants absent from the generated master image.
 *  0..11: two Q->QP digit conversions;
 * 12..26: P->Q correction conversion;
 * 27..30: (P0*P1*P2)^-1 mod Qi.
 */
static const uint32_t fhe_broadcast_values[FHE_BROADCAST_COUNT] = {
    25027601U, 50077697U, 25041905U, 50061313U,
    45276161U, 491520U, 475136U, 50552833U,
    5055489U, 245760U, 229376U, 50307073U,
    82172918U, 11385602U, 22481540U, 34985324U, 15298997U,
    16003190U, 2392495U, 29536542U, 113400U, 14710308U,
    82097047U, 33849659U, 27299937U, 29603404U, 16919882U,
    3242147U, 22123876U, 32538903U, 16525452U,
};

static uint32_t fhe_input_ntt[4][FHE_Q_COUNT][FHE_N];
static uint32_t fhe_tensor[3][FHE_Q_COUNT][FHE_N];
static uint32_t fhe_modup[FHE_BASIS_COUNT][FHE_N];
static uint32_t fhe_acc[2][FHE_BASIS_COUNT][FHE_N];
static uint32_t fhe_final[2][FHE_Q_COUNT][FHE_N];
static int fhe_cpu_validate_checkpoints = 1;
static volatile uint32_t fhe_cpu_sink;

#if !defined(__riscv)
static _Alignas(FHE_LINE_BYTES)
    uint32_t fhe_host_memory[HPU_IT_MEM_LINES * FHE_WORDS_PER_LINE];
#endif

typedef enum {
    FHE_PROGRAM_KEYSWITCH,
    FHE_PROGRAM_RELIN,
    FHE_PROGRAM_CIPHERTEXT_MUL
} fhe_program_kind;

static volatile uint32_t *fhe_memory(void) {
#if defined(__riscv)
    return (volatile uint32_t *)(uintptr_t)HPU_IT_MEM_BASE;
#else
    return fhe_host_memory;
#endif
}

static volatile uint32_t *fhe_memory_line(unsigned line) {
    return fhe_memory() + (size_t)line * FHE_WORDS_PER_LINE;
}

static const uint32_t *fhe_master_words(void) {
    return (const uint32_t *)(const void *)hpu_fhe_master_begin;
}

static const uint32_t *fhe_master_line(unsigned line) {
    return fhe_master_words() + (size_t)line * FHE_WORDS_PER_LINE;
}

static unsigned fhe_ct_line(unsigned operand, unsigned component,
                            unsigned basis) {
    unsigned base = operand == 0U ? FHE_LINE_CTA : FHE_LINE_CTB;
    return base + FHE_POLY_LINES * (FHE_Q_COUNT * component + basis);
}

static unsigned fhe_input_ntt_line(unsigned input, unsigned basis) {
    return FHE_LINE_INPUT_NTT +
           FHE_POLY_LINES * (FHE_Q_COUNT * input + basis);
}

static unsigned fhe_tensor_line(unsigned base, unsigned component,
                                unsigned basis) {
    return base + FHE_POLY_LINES * (FHE_Q_COUNT * component + basis);
}

static unsigned fhe_digit_line(unsigned base, unsigned digit,
                               unsigned basis) {
    return base + FHE_POLY_LINES * (FHE_BASIS_COUNT * digit + basis);
}

static unsigned fhe_acc_line(unsigned base, unsigned component,
                             unsigned basis) {
    return base + FHE_POLY_LINES * (FHE_BASIS_COUNT * component + basis);
}

static unsigned fhe_output_line(unsigned base, unsigned component,
                                unsigned basis) {
    return base + FHE_POLY_LINES * (FHE_Q_COUNT * component + basis);
}

static unsigned fhe_rlk_line(unsigned digit, unsigned component,
                             unsigned basis) {
    return FHE_LINE_RLK + FHE_POLY_LINES *
           ((digit * 2U + component) * FHE_BASIS_COUNT + basis);
}

static unsigned fhe_twiddle_pre_line(unsigned basis) {
    return FHE_LINE_TWIDDLE + FHE_TWIDDLE_BASIS_STRIDE * basis;
}

static unsigned fhe_twiddle_stage_line(unsigned basis, int inverse,
                                        unsigned stage) {
    return fhe_twiddle_pre_line(basis) +
           (inverse ? FHE_TWIDDLE_INTT_STAGE : FHE_TWIDDLE_NTT_STAGE) +
           FHE_STAGE_LINES * stage;
}

static unsigned fhe_twiddle_post_line(unsigned basis) {
    return fhe_twiddle_pre_line(basis) + FHE_TWIDDLE_POST;
}

static unsigned fhe_broadcast_line(unsigned index) {
    return FHE_MASTER_LINES + FHE_BROADCAST_STRIDE * index;
}

static uint64_t fhe_cycle_now(void) {
#if defined(__riscv) && defined(HPU_IT_STANDALONE_HTIF) && \
    HPU_IT_STANDALONE_HTIF
    static uint64_t synthetic_cycle;
    synthetic_cycle += 1U;
    return synthetic_cycle;
#elif defined(__riscv)
    uint64_t value;
    __asm__ volatile("rdcycle %0" : "=r"(value) : : "memory");
    return value;
#else
    return (uint64_t)clock();
#endif
}

static uint32_t fhe_add(uint32_t left, uint32_t right, uint32_t modulus) {
    uint64_t sum = (uint64_t)left + right;
    return (uint32_t)(sum >= modulus ? sum - modulus : sum);
}

static uint32_t fhe_sub(uint32_t left, uint32_t right, uint32_t modulus) {
    return left >= right ? left - right :
           (uint32_t)((uint64_t)left + modulus - right);
}

static uint32_t fhe_mul(uint32_t left, uint32_t right, uint32_t modulus) {
    return (uint32_t)(((uint64_t)left * right) % modulus);
}

static uint32_t fhe_inverse(uint32_t value, uint32_t modulus) {
    int64_t old_coefficient = 1;
    int64_t coefficient = 0;
    int64_t old_remainder = value % modulus;
    int64_t remainder = modulus;
    while (remainder != 0) {
        int64_t quotient = old_remainder / remainder;
        int64_t next_coefficient = old_coefficient - quotient * coefficient;
        int64_t next_remainder = old_remainder - quotient * remainder;
        old_coefficient = coefficient;
        coefficient = next_coefficient;
        old_remainder = remainder;
        remainder = next_remainder;
    }
    if (old_remainder != 1) return 0U;
    old_coefficient %= (int64_t)modulus;
    if (old_coefficient < 0) old_coefficient += modulus;
    return (uint32_t)old_coefficient;
}

static uint64_t fhe_fnv1a64(const uint8_t *data, size_t bytes) {
    uint64_t hash = UINT64_C(14695981039346656037);
    size_t i;
    for (i = 0U; i < bytes; ++i) {
        hash ^= data[i];
        hash *= UINT64_C(1099511628211);
    }
    return hash;
}

static FHE_MAYBE_UNUSED void fhe_fence(void) {
#if defined(__riscv)
    __asm__ volatile("fence iorw, iorw" ::: "memory");
#endif
}

static void fhe_cache_flush(uintptr_t address, size_t bytes) {
#if defined(__riscv)
    uintptr_t cursor = address & ~(uintptr_t)63U;
    uintptr_t end = address + bytes;
    for (; cursor < end; cursor += 64U) {
        __asm__ volatile(".insn i 0x0f, 2, x0, %0, 2"
                         : : "r"(cursor) : "memory");
    }
    fhe_fence();
#else
    (void)address;
    (void)bytes;
#endif
}

static void fhe_cache_invalidate(uintptr_t address, size_t bytes) {
#if defined(__riscv)
    uintptr_t cursor = address & ~(uintptr_t)63U;
    uintptr_t end = address + bytes;
    for (; cursor < end; cursor += 64U) {
        __asm__ volatile(".insn i 0x0f, 2, x0, %0, 0"
                         : : "r"(cursor) : "memory");
    }
    fhe_fence();
#else
    (void)address;
    (void)bytes;
#endif
}

static FHE_MAYBE_UNUSED void fhe_csr_write(unsigned offset, uint32_t value) {
#if HPU_IT_ENABLE_MMIO
    *(volatile uint32_t *)(uintptr_t)(FHE_CSR_BASE + offset) = value;
    fhe_fence();
#else
    (void)offset;
    (void)value;
#endif
}

static FHE_MAYBE_UNUSED uint32_t fhe_csr_read(unsigned offset) {
#if HPU_IT_ENABLE_MMIO
    uint32_t value =
        *(volatile uint32_t *)(uintptr_t)(FHE_CSR_BASE + offset);
    fhe_fence();
    return value;
#else
    (void)offset;
    return 0U;
#endif
}

static int fhe_configure_window(void) {
#if HPU_IT_ENABLE_MMIO
    uintptr_t base = (uintptr_t)fhe_memory();
    uint32_t status;
    volatile unsigned delay;
    fhe_csr_write(FHE_CSR_BASE_LO, (uint32_t)base);
    fhe_csr_write(FHE_CSR_BASE_HI,
                  (uint32_t)(((uint64_t)base >> 32U) & 0xffU));
    fhe_csr_write(FHE_CSR_SIZE_LO, HPU_IT_MEM_LINES);
    fhe_csr_write(FHE_CSR_SIZE_HI, 0U);
    if (fhe_csr_read(FHE_CSR_BASE_LO) != (uint32_t)base ||
        (fhe_csr_read(FHE_CSR_BASE_HI) & 0xffU) !=
            (((uint64_t)base >> 32U) & 0xffU) ||
        fhe_csr_read(FHE_CSR_SIZE_LO) != HPU_IT_MEM_LINES) {
        return 401;
    }
    fhe_csr_write(FHE_CSR_COMMIT, 1U);
    for (delay = 0U; delay < 1024U; ++delay) {
        __asm__ volatile("nop");
    }
    status = fhe_csr_read(FHE_CSR_STATUS);
    if ((status & FHE_STATUS_WINDOW_VALID) == 0U) return 402;
#endif
    return 0;
}

static FHE_MAYBE_UNUSED int fhe_wait_terminal_sync(void) {
#if HPU_IT_WAIT_IRQ
    unsigned timeout;
    for (timeout = 0U; timeout < FHE_IRQ_TIMEOUT; ++timeout) {
        uint32_t fault = fhe_csr_read(FHE_CSR_FAULT);
        if ((fault & 1U) != 0U) {
            printf("HPU_IT_FHE_FAULT raw=0x%x dir=%u obj=%u\n",
                   fault, (fault >> 1U) & 1U, (fault >> 4U) & 7U);
            fhe_csr_write(FHE_CSR_FAULT, 1U);
            return 403;
        }
        if ((fhe_csr_read(FHE_CSR_IRQ) & 1U) != 0U) {
            fhe_csr_write(FHE_CSR_IRQ, 1U);
            fhe_csr_write(FHE_CSR_IRQ, 0U);
            return 0;
        }
    }
    return 404;
#else
    return 0;
#endif
}

static int fhe_validate_master(void) {
    size_t bytes = (size_t)(hpu_fhe_master_end - hpu_fhe_master_begin);
    if (bytes != (size_t)FHE_MASTER_LINES * FHE_LINE_BYTES) return 405;
    if (fhe_fnv1a64(hpu_fhe_master_begin, bytes) !=
        UINT64_C(0xb3cd9960b63475e1)) {
        return 406;
    }
    return 0;
}

static void fhe_poison_region(unsigned first_line, unsigned lines,
                              uint32_t salt) {
    volatile uint32_t *memory = fhe_memory_line(first_line);
    size_t words = (size_t)lines * FHE_WORDS_PER_LINE;
    size_t i;
    for (i = 0U; i < words; ++i) {
        memory[i] = FHE_POISON_WORD ^ salt ^ (uint32_t)i * 0x01010101U;
    }
}

static int fhe_prepare_fixture(fhe_program_kind program) {
    volatile uint32_t *memory = fhe_memory();
    const uint32_t *master = fhe_master_words();
    size_t total_words = (size_t)HPU_IT_MEM_LINES * FHE_WORDS_PER_LINE;
    size_t master_words = (size_t)FHE_MASTER_LINES * FHE_WORDS_PER_LINE;
    size_t i;
    unsigned constant;
    unsigned first_poison;
    unsigned poison_end;
    int rc;

    if (program == FHE_PROGRAM_CIPHERTEXT_MUL) {
        first_poison = FHE_LINE_INPUT_NTT;
        poison_end = FHE_LINE_CIPHER_OUT +
                     2U * FHE_Q_COUNT * FHE_POLY_LINES;
    } else {
        first_poison = FHE_LINE_MODUP_COEFF;
        poison_end = FHE_LINE_CIPHER_OUT +
                     2U * FHE_Q_COUNT * FHE_POLY_LINES;
    }

    if (HPU_IT_MEM_LINES < FHE_REQUIRED_LINES) return 407;
    rc = fhe_validate_master();
    if (rc != 0) return rc;
    for (i = 0U; i < total_words; ++i) memory[i] = FHE_GUARD_WORD;
    for (i = 0U; i < master_words; ++i) memory[i] = master[i];
    for (constant = 0U; constant < FHE_BROADCAST_COUNT; ++constant) {
        volatile uint32_t *destination =
            fhe_memory_line(fhe_broadcast_line(constant));
        for (i = 0U; i < FHE_N; ++i) {
            destination[i] = fhe_broadcast_values[constant];
        }
    }

    /* Standalone poison-backed ModDown scratch follows all broadcasts. */
    for (constant = 0U; constant < FHE_P_COUNT; ++constant) {
        fhe_poison_region(FHE_LINE_SCRATCH + constant * FHE_POLY_LINES,
                          FHE_POLY_LINES,
                          0x53435254U ^ constant ^ (uint32_t)program);
    }
    /* Every contiguous HPU-produced checkpoint and final output starts poison. */
    fhe_poison_region(first_poison, poison_end - first_poison,
                      0x4b535748U ^ (uint32_t)program);
    fhe_cache_flush((uintptr_t)memory,
                    (size_t)HPU_IT_MEM_LINES * FHE_LINE_BYTES);
    return fhe_configure_window();
}

static void fhe_bit_reverse(uint32_t *values) {
    unsigned i;
    unsigned j = 0U;
    for (i = 1U; i < FHE_N; ++i) {
        unsigned bit = FHE_N >> 1U;
        uint32_t temporary;
        while ((j & bit) != 0U) {
            j ^= bit;
            bit >>= 1U;
        }
        j ^= bit;
        if (i >= j) continue;
        temporary = values[i];
        values[i] = values[j];
        values[j] = temporary;
    }
}

static void fhe_cpu_transform(uint32_t *values, unsigned basis,
                              int inverse) {
    uint32_t modulus = fhe_moduli[basis];
    unsigned stage;
    unsigned i;
    if (!inverse) {
        const uint32_t *factor = fhe_master_line(fhe_twiddle_pre_line(basis));
        for (i = 0U; i < FHE_N; ++i) {
            values[i] = fhe_mul(values[i], factor[i], modulus);
        }
    }
    fhe_bit_reverse(values);
    for (stage = 0U; stage < FHE_STAGE_COUNT; ++stage) {
        const uint32_t *twiddle =
            fhe_master_line(fhe_twiddle_stage_line(basis, inverse, stage));
        unsigned half = 1U << stage;
        unsigned group = half << 1U;
        unsigned base;
        unsigned index = 0U;
        for (base = 0U; base < FHE_N; base += group) {
            unsigned j;
            for (j = 0U; j < half; ++j, ++index) {
                uint32_t even = values[base + j];
                uint32_t odd = fhe_mul(values[base + j + half],
                                       twiddle[index], modulus);
                values[base + j] = fhe_add(even, odd, modulus);
                values[base + j + half] = fhe_sub(even, odd, modulus);
            }
        }
    }
    if (inverse) {
        const uint32_t *factor =
            fhe_master_line(fhe_twiddle_post_line(basis));
        for (i = 0U; i < FHE_N; ++i) {
            values[i] = fhe_mul(values[i], factor[i], modulus);
        }
    }
}

static void fhe_copy_poly(uint32_t *destination, const uint32_t *source) {
    unsigned i;
    for (i = 0U; i < FHE_N; ++i) destination[i] = source[i];
}

static int fhe_verify_poly(const char *phase, unsigned line,
                           const uint32_t *actual,
                           const uint32_t *expected) {
    unsigned i;
    for (i = 0U; i < FHE_N; ++i) {
        if (actual[i] != expected[i]) {
            printf("HPU_IT_FHE_MISMATCH phase=%s line=%u word=%u "
                   "actual=0x%x expected=0x%x\n",
                   phase, line + i / FHE_WORDS_PER_LINE,
                   i % FHE_WORDS_PER_LINE, actual[i], expected[i]);
            return 408;
        }
    }
    return 0;
}

static int fhe_record_cpu_poly(const char *phase, unsigned line,
                               const uint32_t *values,
                               int master_is_golden) {
    int rc = 0;
    if (!fhe_cpu_validate_checkpoints) return 0;
    if (master_is_golden) {
        rc = fhe_verify_poly(phase, line, values, fhe_master_line(line));
        if (rc != 0) return rc;
    }
#if !defined(__riscv)
    {
        volatile uint32_t *destination = fhe_memory_line(line);
        unsigned i;
        for (i = 0U; i < FHE_N; ++i) destination[i] = values[i];
    }
#else
    (void)line;
#endif
    return 0;
}

static uint32_t fhe_product_mod(const uint32_t *values, unsigned count,
                                uint32_t modulus) {
    uint32_t product = 1U;
    unsigned i;
    for (i = 0U; i < count; ++i) {
        product = fhe_mul(product, values[i] % modulus, modulus);
    }
    return product;
}

static int fhe_validate_broadcast_math(void) {
    unsigned digit;
    unsigned q;
    unsigned p;
    static const unsigned digit_inverse_index[FHE_DIGITS][2] = {
        {0U, 2U}, {4U, 8U},
    };
    static const unsigned moddown_group[FHE_P_COUNT] = {12U, 17U, 22U};

    for (digit = 0U; digit < FHE_DIGITS; ++digit) {
        unsigned first = digit * 2U;
        unsigned limb;
        for (limb = 0U; limb < 2U; ++limb) {
            unsigned other = first + (limb ^ 1U);
            uint32_t inverse = fhe_inverse(
                fhe_moduli[other] % fhe_moduli[first + limb],
                fhe_moduli[first + limb]);
            if (inverse !=
                fhe_broadcast_values[digit_inverse_index[digit][limb]]) {
                return 409;
            }
        }
    }
    for (p = 0U; p < FHE_P_COUNT; ++p) {
        uint64_t hat = 1U;
        unsigned other;
        for (other = 0U; other < FHE_P_COUNT; ++other) {
            if (other != p) hat *= fhe_moduli[FHE_Q_COUNT + other];
        }
        if (fhe_inverse((uint32_t)(hat %
                        fhe_moduli[FHE_Q_COUNT + p]),
                        fhe_moduli[FHE_Q_COUNT + p]) !=
            fhe_broadcast_values[moddown_group[p]]) {
            return 410;
        }
        for (q = 0U; q < FHE_Q_COUNT; ++q) {
            if ((uint32_t)(hat % fhe_moduli[q]) !=
                fhe_broadcast_values[moddown_group[p] + 1U + q]) {
                return 411;
            }
        }
    }
    for (q = 0U; q < FHE_Q_COUNT; ++q) {
        uint32_t p_product = fhe_product_mod(
            &fhe_moduli[FHE_Q_COUNT], FHE_P_COUNT, fhe_moduli[q]);
        if (fhe_inverse(p_product, fhe_moduli[q]) !=
            fhe_broadcast_values[27U + q]) {
            return 412;
        }
    }
    return 0;
}

static const uint32_t *fhe_tensor_source(fhe_program_kind program,
                                         unsigned component,
                                         unsigned basis) {
    if (program == FHE_PROGRAM_CIPHERTEXT_MUL) {
        return fhe_tensor[component][basis];
    }
    return fhe_master_line(
        fhe_tensor_line(FHE_LINE_TENSOR_COEFF, component, basis));
}

static int fhe_cpu_keyswitch(fhe_program_kind program) {
    unsigned digit;
    unsigned component;
    unsigned basis;
    unsigned i;
    int rc;

    for (component = 0U; component < 2U; ++component) {
        for (basis = 0U; basis < FHE_BASIS_COUNT; ++basis) {
            for (i = 0U; i < FHE_N; ++i) {
                fhe_acc[component][basis][i] = 0U;
            }
        }
    }

    for (digit = 0U; digit < FHE_DIGITS; ++digit) {
        unsigned source_first = digit * 2U;
        const uint32_t *source0 =
            fhe_tensor_source(program, 2U, source_first);
        const uint32_t *source1 =
            fhe_tensor_source(program, 2U, source_first + 1U);
        uint32_t source0_modulus = fhe_moduli[source_first];
        uint32_t source1_modulus = fhe_moduli[source_first + 1U];
        uint32_t inverse0 = fhe_inverse(source1_modulus % source0_modulus,
                                        source0_modulus);
        uint32_t inverse1 = fhe_inverse(source0_modulus % source1_modulus,
                                        source1_modulus);

        for (basis = 0U; basis < FHE_BASIS_COUNT; ++basis) {
            uint32_t target = fhe_moduli[basis];
            if (basis == source_first) {
                fhe_copy_poly(fhe_modup[basis], source0);
            } else if (basis == source_first + 1U) {
                fhe_copy_poly(fhe_modup[basis], source1);
            } else {
                uint32_t hat0 = source1_modulus % target;
                uint32_t hat1 = source0_modulus % target;
                for (i = 0U; i < FHE_N; ++i) {
                    uint32_t normalized0 =
                        fhe_mul(source0[i], inverse0, source0_modulus);
                    uint32_t normalized1 =
                        fhe_mul(source1[i], inverse1, source1_modulus);
                    fhe_modup[basis][i] = fhe_add(
                        fhe_mul(normalized0, hat0, target),
                        fhe_mul(normalized1, hat1, target), target);
                }
            }
            rc = fhe_record_cpu_poly(
                "cpu-modup-coeff",
                fhe_digit_line(FHE_LINE_MODUP_COEFF, digit, basis),
                fhe_modup[basis], 1);
            if (rc != 0) return rc;

            fhe_cpu_transform(fhe_modup[basis], basis, 0);
            rc = fhe_record_cpu_poly(
                "cpu-modup-ntt",
                fhe_digit_line(FHE_LINE_MODUP_NTT, digit, basis),
                fhe_modup[basis], 1);
            if (rc != 0) return rc;

            for (component = 0U; component < 2U; ++component) {
                const uint32_t *rlk = fhe_master_line(
                    fhe_rlk_line(digit, component, basis));
                uint32_t modulus = fhe_moduli[basis];
                for (i = 0U; i < FHE_N; ++i) {
                    uint32_t product =
                        fhe_mul(fhe_modup[basis][i], rlk[i], modulus);
                    fhe_acc[component][basis][i] =
                        digit == 0U ? product :
                        fhe_add(fhe_acc[component][basis][i], product,
                                modulus);
                }
            }
        }
    }

    for (component = 0U; component < 2U; ++component) {
        for (basis = 0U; basis < FHE_BASIS_COUNT; ++basis) {
            rc = fhe_record_cpu_poly(
                "cpu-keyswitch-acc-ntt",
                fhe_acc_line(FHE_LINE_KS_ACC_NTT, component, basis),
                fhe_acc[component][basis], 1);
            if (rc != 0) return rc;
            fhe_cpu_transform(fhe_acc[component][basis], basis, 1);
            rc = fhe_record_cpu_poly(
                "cpu-keyswitch-coeff",
                fhe_acc_line(FHE_LINE_KS_COEFF, component, basis),
                fhe_acc[component][basis], 1);
            if (rc != 0) return rc;
        }
    }

    for (component = 0U; component < 2U; ++component) {
        for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
            uint32_t modulus = fhe_moduli[basis];
            uint32_t p_inverse = fhe_inverse(
                fhe_product_mod(&fhe_moduli[FHE_Q_COUNT], FHE_P_COUNT,
                                modulus),
                modulus);
            for (i = 0U; i < FHE_N; ++i) {
                uint32_t correction = 0U;
                unsigned source;
                for (source = 0U; source < FHE_P_COUNT; ++source) {
                    uint64_t hat = 1U;
                    unsigned other;
                    uint32_t source_modulus =
                        fhe_moduli[FHE_Q_COUNT + source];
                    uint32_t inverse;
                    uint32_t normalized;
                    for (other = 0U; other < FHE_P_COUNT; ++other) {
                        if (other != source) {
                            hat *= fhe_moduli[FHE_Q_COUNT + other];
                        }
                    }
                    inverse = fhe_inverse((uint32_t)(hat % source_modulus),
                                          source_modulus);
                    normalized = fhe_mul(
                        fhe_acc[component][FHE_Q_COUNT + source][i],
                        inverse, source_modulus);
                    correction = fhe_add(
                        correction,
                        fhe_mul(normalized, (uint32_t)(hat % modulus),
                                modulus),
                        modulus);
                }
                fhe_final[component][basis][i] = fhe_mul(
                    fhe_sub(fhe_acc[component][basis][i], correction,
                            modulus),
                    p_inverse, modulus);
            }
            rc = fhe_record_cpu_poly(
                "cpu-keyswitch-moddown",
                fhe_output_line(FHE_LINE_KS_MODDOWN, component, basis),
                fhe_final[component][basis], 1);
            if (rc != 0) return rc;
        }
    }

    /* Materialize the final state of the dedicated three-limb scratch area. */
    for (basis = 0U; basis < FHE_P_COUNT; ++basis) {
        uint32_t modulus = fhe_moduli[FHE_Q_COUNT + basis];
        unsigned inverse_index =
            basis == 0U ? 12U : (basis == 1U ? 17U : 22U);
        for (i = 0U; i < FHE_N; ++i) {
            fhe_modup[basis][i] = fhe_mul(
                fhe_acc[1][FHE_Q_COUNT + basis][i],
                fhe_broadcast_values[inverse_index], modulus);
        }
        rc = fhe_record_cpu_poly(
            "cpu-moddown-scratch",
            FHE_LINE_SCRATCH + basis * FHE_POLY_LINES,
            fhe_modup[basis], 0);
        if (rc != 0) return rc;
    }

    for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
        const uint32_t *base = fhe_tensor_source(program, 0U, basis);
        const uint32_t *second = fhe_tensor_source(program, 1U, basis);
        uint32_t modulus = fhe_moduli[basis];
        for (i = 0U; i < FHE_N; ++i) {
            fhe_final[0][basis][i] =
                fhe_add(base[i], fhe_final[0][basis][i], modulus);
            if (program != FHE_PROGRAM_KEYSWITCH) {
                fhe_final[1][basis][i] =
                    fhe_add(second[i], fhe_final[1][basis][i], modulus);
            }
        }
        rc = fhe_record_cpu_poly(
            "cpu-keyswitch-output0",
            fhe_output_line(FHE_LINE_CIPHER_OUT, 0U, basis),
            fhe_final[0][basis], 1);
        if (rc != 0) return rc;
        rc = fhe_record_cpu_poly(
            "cpu-keyswitch-output1",
            fhe_output_line(FHE_LINE_CIPHER_OUT, 1U, basis),
            fhe_final[1][basis],
            program != FHE_PROGRAM_KEYSWITCH);
        if (rc != 0) return rc;
    }
    return 0;
}

static int fhe_cpu_tensor_multiply(int inverse_to_coeff) {
    unsigned basis;
    unsigned component;
    unsigned i;
    int rc;

    for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
        uint32_t modulus = fhe_moduli[basis];
        for (i = 0U; i < FHE_N; ++i) {
            uint32_t a0b1 = fhe_mul(fhe_input_ntt[0][basis][i],
                                    fhe_input_ntt[3][basis][i], modulus);
            uint32_t a1b0 = fhe_mul(fhe_input_ntt[1][basis][i],
                                    fhe_input_ntt[2][basis][i], modulus);
            fhe_tensor[0][basis][i] =
                fhe_mul(fhe_input_ntt[0][basis][i],
                        fhe_input_ntt[2][basis][i], modulus);
            fhe_tensor[1][basis][i] = fhe_add(a0b1, a1b0, modulus);
            fhe_tensor[2][basis][i] =
                fhe_mul(fhe_input_ntt[1][basis][i],
                        fhe_input_ntt[3][basis][i], modulus);
        }
        for (component = 0U; component < 3U; ++component) {
            rc = fhe_record_cpu_poly(
                "cpu-tensor-ntt",
                fhe_tensor_line(FHE_LINE_TENSOR_NTT, component, basis),
                fhe_tensor[component][basis], 1);
            if (rc != 0) return rc;
            if (inverse_to_coeff) {
                fhe_cpu_transform(fhe_tensor[component][basis], basis, 1);
                rc = fhe_record_cpu_poly(
                    "cpu-tensor-coeff",
                    fhe_tensor_line(FHE_LINE_TENSOR_COEFF, component,
                                    basis),
                    fhe_tensor[component][basis], 1);
                if (rc != 0) return rc;
            }
        }
    }
    return 0;
}

static int fhe_cpu_ciphertext_multiply(void) {
    unsigned input;
    unsigned basis;
    int rc;

    for (input = 0U; input < 4U; ++input) {
        unsigned operand = input < 2U ? 0U : 1U;
        unsigned source_component = input & 1U;
        for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
            fhe_copy_poly(fhe_input_ntt[input][basis],
                          fhe_master_line(fhe_ct_line(
                              operand, source_component, basis)));
            fhe_cpu_transform(fhe_input_ntt[input][basis], basis, 0);
            rc = fhe_record_cpu_poly(
                "cpu-input-ntt", fhe_input_ntt_line(input, basis),
                fhe_input_ntt[input][basis], 1);
            if (rc != 0) return rc;
        }
    }
    rc = fhe_cpu_tensor_multiply(1);
    if (rc != 0) return rc;
    return fhe_cpu_keyswitch(FHE_PROGRAM_CIPHERTEXT_MUL);
}

static int fhe_cpu_oracle(fhe_program_kind program) {
    if (fhe_cpu_validate_checkpoints) {
        int rc = fhe_validate_broadcast_math();
        if (rc != 0) return rc;
    }
    if (program == FHE_PROGRAM_CIPHERTEXT_MUL) {
        return fhe_cpu_ciphertext_multiply();
    }
    return fhe_cpu_keyswitch(program);
}

static int fhe_verify_cpu_final(fhe_program_kind program) {
    unsigned component;
    unsigned basis;
    for (component = 0U; component < 2U; ++component) {
        for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
            unsigned line =
                program == FHE_PROGRAM_KEYSWITCH && component == 1U ?
                    fhe_output_line(FHE_LINE_KS_MODDOWN, component, basis) :
                    fhe_output_line(FHE_LINE_CIPHER_OUT, component, basis);
            int rc = fhe_verify_poly("cpu-final-only", line,
                                     fhe_final[component][basis],
                                     fhe_master_line(line));
            if (rc != 0) return rc;
        }
    }
    return 0;
}

#if defined(__riscv)
#if !HPU_IT_USE_GENERATED_FHE
static int fhe_dload(unsigned object, unsigned line, unsigned lines,
                     int mod_table) {
    hpu_dma_span span;
    if (lines == 0U || line > HPU_IT_MEM_LINES ||
        lines > HPU_IT_MEM_LINES - line) {
        return 413;
    }
    span.line_offset = line;
    span.line_count = lines;
    if (mod_table) {
        if (object != 4U || lines != 1U) return 414;
        hpu_dload_mod_p4(span);
        return 0;
    }
    switch (object) {
    case 0U: hpu_dload_poly_p0(span); break;
    case 1U: hpu_dload_poly_p1(span); break;
    case 2U: hpu_dload_poly_p2(span); break;
    case 3U: hpu_dload_poly_p3(span); break;
    case 4U: hpu_dload_poly_p4(span); break;
    case 5U: hpu_dload_poly_p5(span); break;
    case 6U: hpu_dload_poly_p6(span); break;
    case 7U: hpu_dload_poly_p7(span); break;
    default: return 415;
    }
    return 0;
}

static int fhe_dstore(unsigned object, unsigned line, unsigned lines) {
    hpu_dma_span span;
    if (lines == 0U || line > HPU_IT_MEM_LINES ||
        lines > HPU_IT_MEM_LINES - line) {
        return 416;
    }
    span.line_offset = line;
    span.line_count = lines;
    switch (object) {
    case 0U: hpu_dstore_poly_p0_release(span); break;
    case 1U: hpu_dstore_poly_p1_release(span); break;
    case 2U: hpu_dstore_poly_p2_release(span); break;
    case 3U: hpu_dstore_poly_p3_release(span); break;
    case 4U: hpu_dstore_poly_p4_release(span); break;
    case 5U: hpu_dstore_poly_p5_release(span); break;
    case 6U: hpu_dstore_poly_p6_release(span); break;
    case 7U: hpu_dstore_poly_p7_release(span); break;
    default: return 417;
    }
    return 0;
}

static int fhe_pmodld(unsigned basis) {
    switch (basis) {
    case 0U: hpu_pmodld_0(); break;
    case 1U: hpu_pmodld_1(); break;
    case 2U: hpu_pmodld_2(); break;
    case 3U: hpu_pmodld_3(); break;
    case 4U: hpu_pmodld_4(); break;
    case 5U: hpu_pmodld_5(); break;
    case 6U: hpu_pmodld_6(); break;
    default: return 418;
    }
    return 0;
}

static void fhe_stage_p0_p3(int inverse, unsigned stage) {
    if (!inverse) {
        switch (stage) {
        case 0U: HPU_WORD(0x40c0000bU); break;
        case 1U: HPU_WORD(0x40c0040bU); break;
        case 2U: HPU_WORD(0x40c0080bU); break;
        case 3U: HPU_WORD(0x40c00c0bU); break;
        case 4U: HPU_WORD(0x40c0100bU); break;
        case 5U: HPU_WORD(0x40c0140bU); break;
        case 6U: HPU_WORD(0x40c0180bU); break;
        case 7U: HPU_WORD(0x40c01c0bU); break;
        case 8U: HPU_WORD(0x40c0200bU); break;
        case 9U: HPU_WORD(0x40c0240bU); break;
        case 10U: HPU_WORD(0x40c0280bU); break;
        case 11U: HPU_WORD(0x40c02c0bU); break;
        default: break;
        }
    } else {
        switch (stage) {
        case 0U: HPU_WORD(0x50c0000bU); break;
        case 1U: HPU_WORD(0x50c0040bU); break;
        case 2U: HPU_WORD(0x50c0080bU); break;
        case 3U: HPU_WORD(0x50c00c0bU); break;
        case 4U: HPU_WORD(0x50c0100bU); break;
        case 5U: HPU_WORD(0x50c0140bU); break;
        case 6U: HPU_WORD(0x50c0180bU); break;
        case 7U: HPU_WORD(0x50c01c0bU); break;
        case 8U: HPU_WORD(0x50c0200bU); break;
        case 9U: HPU_WORD(0x50c0240bU); break;
        case 10U: HPU_WORD(0x50c0280bU); break;
        case 11U: HPU_WORD(0x50c02c0bU); break;
        default: break;
        }
    }
}

static int fhe_issue_transform(unsigned input_line, unsigned output_line,
                               unsigned basis, int inverse) {
    unsigned stage;
    int rc = fhe_pmodld(basis);
    if (rc == 0) rc = fhe_dload(0U, input_line, FHE_POLY_LINES, 0);
    if (rc == 0 && !inverse) {
        rc = fhe_dload(3U, fhe_twiddle_pre_line(basis),
                       FHE_POLY_LINES, 0);
        if (rc == 0) {
            /* Explicitly bind the pre-twist object in p3. */
            HPU_WORD(0x2000c00bU);
        }
        if (rc == 0) hpu_pfree(3U);
    }
    for (stage = 0U; rc == 0 && stage < FHE_STAGE_COUNT; ++stage) {
        rc = fhe_dload(3U, fhe_twiddle_stage_line(basis, inverse, stage),
                       FHE_STAGE_LINES, 0);
        if (rc == 0) fhe_stage_p0_p3(inverse, stage);
        if (rc == 0) hpu_pfree(3U);
    }
    if (rc == 0 && inverse) {
        rc = fhe_dload(3U, fhe_twiddle_post_line(basis),
                       FHE_POLY_LINES, 0);
        if (rc == 0) HPU_WORD(0x2000c00bU); /* pmul p0,p0,p3 */
        if (rc == 0) hpu_pfree(3U);
    }
    if (rc == 0) rc = fhe_dstore(0U, output_line, FHE_POLY_LINES);
    return rc;
}

static unsigned fhe_modup_inverse_index(unsigned digit, unsigned limb) {
    static const unsigned indices[FHE_DIGITS][2] = {
        {0U, 2U}, {4U, 8U},
    };
    return indices[digit][limb];
}

static unsigned fhe_modup_hat_index(unsigned digit, unsigned limb,
                                    unsigned target) {
    if (digit == 0U) return limb == 0U ? 1U : 3U;
    if (limb == 0U) {
        if (target == 0U) return 5U;
        if (target == 1U) return 6U;
        return 7U;
    }
    if (target == 0U) return 9U;
    if (target == 1U) return 10U;
    return 11U;
}

static int fhe_issue_modup(unsigned digit) {
    unsigned source_first = digit * 2U;
    unsigned limb;
    unsigned target;
    int rc = 0;

    for (limb = 0U; rc == 0 && limb < 2U; ++limb) {
        unsigned source_basis = source_first + limb;
        unsigned source_line = fhe_tensor_line(
            FHE_LINE_TENSOR_COEFF, 2U, source_basis);
        unsigned output_line = fhe_digit_line(
            FHE_LINE_MODUP_COEFF, digit, source_basis);
        unsigned scratch_line = FHE_LINE_SCRATCH + limb * FHE_POLY_LINES;

        rc = fhe_dload(0U, source_line, FHE_POLY_LINES, 0);
        if (rc == 0) rc = fhe_dstore(0U, output_line, FHE_POLY_LINES);

        if (rc == 0) rc = fhe_pmodld(source_basis);
        if (rc == 0) rc = fhe_dload(0U, source_line, FHE_POLY_LINES, 0);
        if (rc == 0) {
            rc = fhe_dload(1U,
                           fhe_broadcast_line(
                               fhe_modup_inverse_index(digit, limb)),
                           FHE_POLY_LINES, 0);
        }
        if (rc == 0) hpu_pmul_p0_p0_p1();
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) rc = fhe_dstore(0U, scratch_line, FHE_POLY_LINES);
    }

    for (target = 0U; rc == 0 && target < FHE_BASIS_COUNT; ++target) {
        if (target == source_first || target == source_first + 1U) continue;
        rc = fhe_pmodld(target);
        for (limb = 0U; rc == 0 && limb < 2U; ++limb) {
            rc = fhe_dload(0U,
                           FHE_LINE_SCRATCH + limb * FHE_POLY_LINES,
                           FHE_POLY_LINES, 0);
            if (rc == 0) {
                rc = fhe_dload(1U,
                               fhe_broadcast_line(
                                   fhe_modup_hat_index(digit, limb,
                                                       target)),
                               FHE_POLY_LINES, 0);
            }
            if (rc == 0) {
                if (limb == 0U) hpu_pmul_p2_p0_p1();
                else hpu_pmac_p2_p0_p1();
            }
            if (rc == 0) hpu_pfree(0U);
            if (rc == 0) hpu_pfree(1U);
        }
        if (rc == 0) {
            rc = fhe_dstore(
                2U, fhe_digit_line(FHE_LINE_MODUP_COEFF, digit, target),
                FHE_POLY_LINES);
        }
    }
    return rc;
}

static int fhe_issue_moddown_component(unsigned component) {
    static const unsigned group[FHE_P_COUNT] = {12U, 17U, 22U};
    unsigned source;
    unsigned basis;
    int rc = 0;

    for (source = 0U; rc == 0 && source < FHE_P_COUNT; ++source) {
        unsigned source_basis = FHE_Q_COUNT + source;
        rc = fhe_pmodld(source_basis);
        if (rc == 0) {
            rc = fhe_dload(
                0U, fhe_acc_line(FHE_LINE_KS_COEFF, component, source_basis),
                FHE_POLY_LINES, 0);
        }
        if (rc == 0) {
            rc = fhe_dload(1U, fhe_broadcast_line(group[source]),
                           FHE_POLY_LINES, 0);
        }
        if (rc == 0) hpu_pmul_p0_p0_p1();
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) {
            rc = fhe_dstore(0U,
                            FHE_LINE_SCRATCH + source * FHE_POLY_LINES,
                            FHE_POLY_LINES);
        }
    }

    for (basis = 0U; rc == 0 && basis < FHE_Q_COUNT; ++basis) {
        rc = fhe_pmodld(basis);
        for (source = 0U; rc == 0 && source < FHE_P_COUNT; ++source) {
            rc = fhe_dload(
                0U, FHE_LINE_SCRATCH + source * FHE_POLY_LINES,
                FHE_POLY_LINES, 0);
            if (rc == 0) {
                rc = fhe_dload(
                    1U, fhe_broadcast_line(group[source] + 1U + basis),
                    FHE_POLY_LINES, 0);
            }
            if (rc == 0) {
                if (source == 0U) hpu_pmul_p2_p0_p1();
                else hpu_pmac_p2_p0_p1();
            }
            if (rc == 0) hpu_pfree(0U);
            if (rc == 0) hpu_pfree(1U);
        }
        if (rc == 0) {
            rc = fhe_dload(
                0U, fhe_acc_line(FHE_LINE_KS_COEFF, component, basis),
                FHE_POLY_LINES, 0);
        }
        if (rc == 0) HPU_WORD(0x1400800bU); /* psub p2,p0,p2 */
        if (rc == 0) hpu_pfree(0U);
        if (rc == 0) {
            rc = fhe_dload(1U, fhe_broadcast_line(27U + basis),
                           FHE_POLY_LINES, 0);
        }
        if (rc == 0) hpu_pmul_p2_p2_p1();
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) {
            rc = fhe_dstore(
                2U, fhe_output_line(FHE_LINE_KS_MODDOWN,
                                    component, basis),
                FHE_POLY_LINES);
        }
    }
    return rc;
}

static int fhe_issue_keyswitch(fhe_program_kind program) {
    unsigned digit;
    unsigned component;
    unsigned basis;
    int rc = 0;

    for (digit = 0U; rc == 0 && digit < FHE_DIGITS; ++digit) {
        rc = fhe_issue_modup(digit);
        for (basis = 0U; rc == 0 && basis < FHE_BASIS_COUNT; ++basis) {
            rc = fhe_issue_transform(
                fhe_digit_line(FHE_LINE_MODUP_COEFF, digit, basis),
                fhe_digit_line(FHE_LINE_MODUP_NTT, digit, basis),
                basis, 0);
        }
        for (component = 0U; rc == 0 && component < 2U; ++component) {
            for (basis = 0U; rc == 0 && basis < FHE_BASIS_COUNT; ++basis) {
                rc = fhe_pmodld(basis);
                if (rc == 0) {
                    rc = fhe_dload(
                        0U, fhe_digit_line(FHE_LINE_MODUP_NTT,
                                          digit, basis),
                        FHE_POLY_LINES, 0);
                }
                if (rc == 0) {
                    rc = fhe_dload(1U, fhe_rlk_line(digit, component, basis),
                                   FHE_POLY_LINES, 0);
                }
                if (rc == 0 && digit != 0U) {
                    rc = fhe_dload(
                        2U, fhe_acc_line(FHE_LINE_KS_ACC_NTT,
                                        component, basis),
                        FHE_POLY_LINES, 0);
                }
                if (rc == 0) {
                    if (digit == 0U) hpu_pmul_p2_p0_p1();
                    else hpu_pmac_p2_p0_p1();
                }
                if (rc == 0) hpu_pfree(0U);
                if (rc == 0) hpu_pfree(1U);
                if (rc == 0) {
                    rc = fhe_dstore(
                        2U, fhe_acc_line(FHE_LINE_KS_ACC_NTT,
                                        component, basis),
                        FHE_POLY_LINES);
                }
            }
        }
    }

    for (component = 0U; rc == 0 && component < 2U; ++component) {
        for (basis = 0U; rc == 0 && basis < FHE_BASIS_COUNT; ++basis) {
            rc = fhe_issue_transform(
                fhe_acc_line(FHE_LINE_KS_ACC_NTT, component, basis),
                fhe_acc_line(FHE_LINE_KS_COEFF, component, basis),
                basis, 1);
        }
    }
    for (component = 0U; rc == 0 && component < 2U; ++component) {
        rc = fhe_issue_moddown_component(component);
    }

    for (basis = 0U; rc == 0 && basis < FHE_Q_COUNT; ++basis) {
        rc = fhe_pmodld(basis);
        if (rc == 0) {
            rc = fhe_dload(0U,
                           fhe_output_line(FHE_LINE_KS_MODDOWN, 0U, basis),
                           FHE_POLY_LINES, 0);
        }
        if (rc == 0) {
            rc = fhe_dload(
                1U, fhe_tensor_line(FHE_LINE_TENSOR_COEFF, 0U, basis),
                FHE_POLY_LINES, 0);
        }
        if (rc == 0) hpu_padd_p2_p0_p1();
        if (rc == 0) hpu_pfree(0U);
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) {
            rc = fhe_dstore(
                2U, fhe_output_line(FHE_LINE_CIPHER_OUT, 0U, basis),
                FHE_POLY_LINES);
        }

        if (rc == 0) {
            rc = fhe_dload(0U,
                           fhe_output_line(FHE_LINE_KS_MODDOWN, 1U, basis),
                           FHE_POLY_LINES, 0);
        }
        if (rc == 0 && program == FHE_PROGRAM_KEYSWITCH) {
            rc = fhe_dstore(
                0U, fhe_output_line(FHE_LINE_CIPHER_OUT, 1U, basis),
                FHE_POLY_LINES);
        } else if (rc == 0) {
            rc = fhe_dload(
                1U, fhe_tensor_line(FHE_LINE_TENSOR_COEFF, 1U, basis),
                FHE_POLY_LINES, 0);
            if (rc == 0) hpu_padd_p2_p0_p1();
            if (rc == 0) hpu_pfree(0U);
            if (rc == 0) hpu_pfree(1U);
            if (rc == 0) {
                rc = fhe_dstore(
                    2U, fhe_output_line(FHE_LINE_CIPHER_OUT, 1U, basis),
                    FHE_POLY_LINES);
            }
        }
    }
    return rc;
}

static int fhe_issue_tensor_multiply(void) {
    unsigned basis;
    int rc = 0;

    for (basis = 0U; rc == 0 && basis < FHE_Q_COUNT; ++basis) {
        rc = fhe_pmodld(basis);
        if (rc == 0) rc = fhe_dload(0U, fhe_input_ntt_line(0U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) rc = fhe_dload(1U, fhe_input_ntt_line(2U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) hpu_pmul_p2_p0_p1();
        if (rc == 0) hpu_pfree(0U);
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) rc = fhe_dstore(
            2U, fhe_tensor_line(FHE_LINE_TENSOR_NTT, 0U, basis),
            FHE_POLY_LINES);

        if (rc == 0) rc = fhe_dload(0U, fhe_input_ntt_line(0U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) rc = fhe_dload(1U, fhe_input_ntt_line(3U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) hpu_pmul_p2_p0_p1();
        if (rc == 0) hpu_pfree(0U);
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) rc = fhe_dload(0U, fhe_input_ntt_line(1U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) rc = fhe_dload(1U, fhe_input_ntt_line(2U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) hpu_pmac_p2_p0_p1();
        if (rc == 0) hpu_pfree(0U);
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) rc = fhe_dstore(
            2U, fhe_tensor_line(FHE_LINE_TENSOR_NTT, 1U, basis),
            FHE_POLY_LINES);

        if (rc == 0) rc = fhe_dload(0U, fhe_input_ntt_line(1U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) rc = fhe_dload(1U, fhe_input_ntt_line(3U, basis),
                                    FHE_POLY_LINES, 0);
        if (rc == 0) hpu_pmul_p2_p0_p1();
        if (rc == 0) hpu_pfree(0U);
        if (rc == 0) hpu_pfree(1U);
        if (rc == 0) rc = fhe_dstore(
            2U, fhe_tensor_line(FHE_LINE_TENSOR_NTT, 2U, basis),
            FHE_POLY_LINES);
    }
    return rc;
}

static int fhe_issue_ciphertext_prefix(void) {
    unsigned input;
    unsigned basis;
    unsigned component;
    int rc = 0;

    for (input = 0U; rc == 0 && input < 4U; ++input) {
        unsigned operand = input < 2U ? 0U : 1U;
        unsigned source_component = input & 1U;
        for (basis = 0U; rc == 0 && basis < FHE_Q_COUNT; ++basis) {
            rc = fhe_issue_transform(
                fhe_ct_line(operand, source_component, basis),
                fhe_input_ntt_line(input, basis), basis, 0);
        }
    }

    if (rc == 0) rc = fhe_issue_tensor_multiply();

    for (component = 0U; rc == 0 && component < 3U; ++component) {
        for (basis = 0U; rc == 0 && basis < FHE_Q_COUNT; ++basis) {
            rc = fhe_issue_transform(
                fhe_tensor_line(FHE_LINE_TENSOR_NTT, component, basis),
                fhe_tensor_line(FHE_LINE_TENSOR_COEFF, component, basis),
                basis, 1);
        }
    }
    return rc;
}

#endif /* !HPU_IT_USE_GENERATED_FHE */

#endif /* defined(__riscv) */

#if HPU_IT_USE_GENERATED_FHE
static void fhe_generated_span(hpu_dma_span_t *span, unsigned line,
                               unsigned lines) {
    span->line_offset = line;
    span->line_count = lines;
}

static void fhe_generated_modup(hpu_dma_span_t *spans, unsigned *dma,
                                unsigned digit) {
    static const unsigned inverse_index[FHE_DIGITS][2] = {
        {0U, 2U}, {4U, 8U},
    };
    unsigned source_first = digit * 2U;
    unsigned source;
    unsigned target;
    for (source = 0U; source < 2U; ++source) {
        unsigned basis = source_first + source;
        fhe_generated_span(&spans[(*dma)++],
                           fhe_tensor_line(FHE_LINE_TENSOR_COEFF, 2U, basis),
                           FHE_POLY_LINES);
        fhe_generated_span(&spans[(*dma)++],
                           fhe_digit_line(FHE_LINE_MODUP_COEFF, digit, basis),
                           FHE_POLY_LINES);
    }
    fhe_generated_span(&spans[(*dma)++], FHE_LINE_MOD_CTX, 1U);
    for (source = 0U; source < 2U; ++source) {
        unsigned basis = source_first + source;
        fhe_generated_span(&spans[(*dma)++],
                           fhe_tensor_line(FHE_LINE_TENSOR_COEFF, 2U, basis),
                           FHE_POLY_LINES);
        fhe_generated_span(&spans[(*dma)++],
                           fhe_broadcast_line(inverse_index[digit][source]),
                           FHE_POLY_LINES);
        fhe_generated_span(&spans[(*dma)++],
                           FHE_LINE_SCRATCH + source * FHE_POLY_LINES,
                           FHE_POLY_LINES);
    }
    for (target = 0U; target < FHE_BASIS_COUNT; ++target) {
        unsigned hat[2];
        if (target == source_first || target == source_first + 1U) continue;
        if (digit == 0U) {
            hat[0] = 1U;
            hat[1] = 3U;
        } else {
            hat[0] = target == 0U ? 5U : (target == 1U ? 6U : 7U);
            hat[1] = target == 0U ? 9U : (target == 1U ? 10U : 11U);
        }
        for (source = 0U; source < 2U; ++source) {
            fhe_generated_span(&spans[(*dma)++],
                               FHE_LINE_SCRATCH + source * FHE_POLY_LINES,
                               FHE_POLY_LINES);
            fhe_generated_span(&spans[(*dma)++], fhe_broadcast_line(hat[source]),
                               FHE_POLY_LINES);
        }
        fhe_generated_span(&spans[(*dma)++],
                           fhe_digit_line(FHE_LINE_MODUP_COEFF, digit, target),
                           FHE_POLY_LINES);
    }
}

static void fhe_generated_ntt_basis(hpu_dma_span_t *spans, unsigned *dma,
                                    unsigned input_line,
                                    unsigned output_line,
                                    unsigned basis) {
    unsigned stage;
    fhe_generated_span(&spans[(*dma)++], input_line, FHE_POLY_LINES);
    fhe_generated_span(&spans[(*dma)++], fhe_twiddle_pre_line(basis),
                       FHE_POLY_LINES);
    for (stage = 0U; stage < FHE_STAGE_COUNT; ++stage) {
        fhe_generated_span(&spans[(*dma)++],
                           fhe_twiddle_stage_line(basis, 0, stage),
                           FHE_STAGE_LINES);
    }
    fhe_generated_span(&spans[(*dma)++], output_line, FHE_POLY_LINES);
}

static void fhe_generated_intt_basis(hpu_dma_span_t *spans, unsigned *dma,
                                     unsigned input_line,
                                     unsigned output_line,
                                     unsigned basis) {
    unsigned stage;
    fhe_generated_span(&spans[(*dma)++], input_line, FHE_POLY_LINES);
    for (stage = 0U; stage < FHE_STAGE_COUNT; ++stage) {
        fhe_generated_span(&spans[(*dma)++],
                           fhe_twiddle_stage_line(basis, 1, stage),
                           FHE_STAGE_LINES);
    }
    fhe_generated_span(&spans[(*dma)++], fhe_twiddle_post_line(basis),
                       FHE_POLY_LINES);
    fhe_generated_span(&spans[(*dma)++], output_line, FHE_POLY_LINES);
}

static void fhe_generated_moddown(hpu_dma_span_t *spans, unsigned *dma,
                                  unsigned component) {
    static const unsigned groups[FHE_P_COUNT] = {12U, 17U, 22U};
    unsigned source;
    unsigned basis;
    fhe_generated_span(&spans[(*dma)++], FHE_LINE_MOD_CTX, 1U);
    for (source = 0U; source < FHE_P_COUNT; ++source) {
        fhe_generated_span(
            &spans[(*dma)++],
            fhe_acc_line(FHE_LINE_KS_COEFF, component, FHE_Q_COUNT + source),
            FHE_POLY_LINES);
        fhe_generated_span(&spans[(*dma)++],
                           fhe_broadcast_line(groups[source]),
                           FHE_POLY_LINES);
        fhe_generated_span(&spans[(*dma)++],
                           FHE_LINE_SCRATCH + source * FHE_POLY_LINES,
                           FHE_POLY_LINES);
    }
    for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
        for (source = 0U; source < FHE_P_COUNT; ++source) {
            fhe_generated_span(&spans[(*dma)++],
                               FHE_LINE_SCRATCH + source * FHE_POLY_LINES,
                               FHE_POLY_LINES);
            fhe_generated_span(&spans[(*dma)++],
                               fhe_broadcast_line(groups[source] + 1U + basis),
                               FHE_POLY_LINES);
        }
        fhe_generated_span(
            &spans[(*dma)++],
            fhe_output_line(FHE_LINE_KS_MODDOWN, component, basis),
            FHE_POLY_LINES);
    }
    fhe_generated_span(&spans[(*dma)++], FHE_LINE_MOD_CTX, 1U);
    for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
        fhe_generated_span(
            &spans[(*dma)++],
            fhe_acc_line(FHE_LINE_KS_COEFF, component, basis),
            FHE_POLY_LINES);
        fhe_generated_span(
            &spans[(*dma)++],
            fhe_output_line(FHE_LINE_KS_MODDOWN, component, basis),
            FHE_POLY_LINES);
        fhe_generated_span(&spans[(*dma)++],
                           fhe_broadcast_line(27U + basis),
                           FHE_POLY_LINES);
        fhe_generated_span(
            &spans[(*dma)++],
            fhe_output_line(FHE_LINE_KS_MODDOWN, component, basis),
            FHE_POLY_LINES);
    }
}

static unsigned fhe_generated_keyswitch_spans(hpu_dma_span_t *spans) {
    unsigned dma = 0U;
    unsigned digit;
    unsigned component;
    unsigned basis;
    for (digit = 0U; digit < FHE_DIGITS; ++digit) {
        fhe_generated_modup(spans, &dma, digit);
        fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
        for (basis = 0U; basis < FHE_BASIS_COUNT; ++basis) {
            fhe_generated_ntt_basis(
                spans, &dma,
                fhe_digit_line(FHE_LINE_MODUP_COEFF, digit, basis),
                fhe_digit_line(FHE_LINE_MODUP_NTT, digit, basis), basis);
        }
        for (component = 0U; component < 2U; ++component) {
            for (basis = 0U; basis < FHE_BASIS_COUNT; ++basis) {
                fhe_generated_span(
                    &spans[dma++],
                    fhe_digit_line(FHE_LINE_MODUP_NTT, digit, basis),
                    FHE_POLY_LINES);
                fhe_generated_span(&spans[dma++],
                                   fhe_rlk_line(digit, component, basis),
                                   FHE_POLY_LINES);
                if (digit != 0U) {
                    fhe_generated_span(
                        &spans[dma++],
                        fhe_acc_line(FHE_LINE_KS_ACC_NTT, component, basis),
                        FHE_POLY_LINES);
                }
                fhe_generated_span(
                    &spans[dma++],
                    fhe_acc_line(FHE_LINE_KS_ACC_NTT, component, basis),
                    FHE_POLY_LINES);
            }
        }
    }
    fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
    for (component = 0U; component < 2U; ++component) {
        for (basis = 0U; basis < FHE_BASIS_COUNT; ++basis) {
            fhe_generated_intt_basis(
                spans, &dma,
                fhe_acc_line(FHE_LINE_KS_ACC_NTT, component, basis),
                fhe_acc_line(FHE_LINE_KS_COEFF, component, basis), basis);
        }
    }
    for (component = 0U; component < 2U; ++component)
        fhe_generated_moddown(spans, &dma, component);
    fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
    for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
        fhe_generated_span(
            &spans[dma++],
            fhe_output_line(FHE_LINE_KS_MODDOWN, 0U, basis),
            FHE_POLY_LINES);
        fhe_generated_span(
            &spans[dma++],
            fhe_tensor_line(FHE_LINE_TENSOR_COEFF, 0U, basis),
            FHE_POLY_LINES);
        fhe_generated_span(
            &spans[dma++],
            fhe_output_line(FHE_LINE_CIPHER_OUT, 0U, basis),
            FHE_POLY_LINES);
    }
    return dma;
}

static unsigned fhe_generated_relin_spans(hpu_dma_span_t *spans) {
    unsigned dma = fhe_generated_keyswitch_spans(spans);
    unsigned basis;
    fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
    for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
        fhe_generated_span(
            &spans[dma++],
            fhe_tensor_line(FHE_LINE_TENSOR_COEFF, 1U, basis),
            FHE_POLY_LINES);
        fhe_generated_span(
            &spans[dma++],
            fhe_output_line(FHE_LINE_KS_MODDOWN, 1U, basis),
            FHE_POLY_LINES);
        fhe_generated_span(
            &spans[dma++],
            fhe_output_line(FHE_LINE_CIPHER_OUT, 1U, basis),
            FHE_POLY_LINES);
    }
    return dma;
}

static unsigned fhe_generated_ciphertext_spans(hpu_dma_span_t *spans) {
    unsigned dma = 0U;
    unsigned component;
    unsigned input;
    unsigned basis;
    fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
    for (component = 0U; component < 2U; ++component) {
        for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
            fhe_generated_ntt_basis(
                spans, &dma, fhe_ct_line(0U, component, basis),
                fhe_input_ntt_line(component, basis), basis);
        }
    }
    fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
    for (component = 0U; component < 2U; ++component) {
        input = 2U + component;
        for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
            fhe_generated_ntt_basis(
                spans, &dma, fhe_ct_line(1U, component, basis),
                fhe_input_ntt_line(input, basis), basis);
        }
    }
    fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
    for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
#define FHE_GEN_INPUT(index_) fhe_input_ntt_line((index_), basis)
#define FHE_GEN_TENSOR(index_) \
        fhe_tensor_line(FHE_LINE_TENSOR_NTT, (index_), basis)
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(0U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(2U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_TENSOR(0U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(0U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(3U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(1U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(2U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_TENSOR(1U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(1U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_INPUT(3U), FHE_POLY_LINES);
        fhe_generated_span(&spans[dma++], FHE_GEN_TENSOR(2U), FHE_POLY_LINES);
#undef FHE_GEN_INPUT
#undef FHE_GEN_TENSOR
    }
    fhe_generated_span(&spans[dma++], FHE_LINE_MOD_CTX, 1U);
    for (component = 0U; component < 3U; ++component) {
        for (basis = 0U; basis < FHE_Q_COUNT; ++basis) {
            fhe_generated_intt_basis(
                spans, &dma,
                fhe_tensor_line(FHE_LINE_TENSOR_NTT, component, basis),
                fhe_tensor_line(FHE_LINE_TENSOR_COEFF, component, basis),
                basis);
        }
    }
    dma += fhe_generated_relin_spans(spans + dma);
    return dma;
}
#endif

int hpu_fhe_resolve_generated_program(hpu_case_kind kind,
                                      hpu_dma_span_t *spans,
                                      size_t span_capacity,
                                      size_t *span_count) {
#if HPU_IT_USE_GENERATED_FHE
    unsigned count;
    if (spans == NULL || span_count == NULL) return 426;
    if (kind == HPU_CASE_CMB_KEYSWITCH ||
        kind == HPU_CASE_PERF_KEYSWITCH) {
        if (span_capacity < HPU_PROGRAM_KEYSWITCH_DMA_COUNT) return 427;
        count = fhe_generated_keyswitch_spans(spans);
        if (count != HPU_PROGRAM_KEYSWITCH_DMA_COUNT) return 428;
    } else if (kind == HPU_CASE_CMB_RELINE ||
               kind == HPU_CASE_PERF_RELIN) {
        if (span_capacity < HPU_PROGRAM_RELINEARIZATION_DMA_COUNT) return 429;
        count = fhe_generated_relin_spans(spans);
        if (count != HPU_PROGRAM_RELINEARIZATION_DMA_COUNT) return 430;
    } else if (kind == HPU_CASE_CMB_HMUL ||
               kind == HPU_CASE_PERF_CIPHERTEXT_MUL ||
               kind == HPU_CASE_APP_MINI_FHE) {
        if (span_capacity < HPU_PROGRAM_CIPHERTEXT_MULTIPLY_DMA_COUNT)
            return 431;
        count = fhe_generated_ciphertext_spans(spans);
        if (count != HPU_PROGRAM_CIPHERTEXT_MULTIPLY_DMA_COUNT) return 432;
    } else {
        return 433;
    }
    *span_count = count;
    return 0;
#else
    (void)kind;
    (void)spans;
    (void)span_capacity;
    (void)span_count;
    return 434;
#endif
}

#if defined(__riscv)

static int fhe_issue_program(fhe_program_kind program) {
#if HPU_IT_USE_GENERATED_FHE
    hpu_dma_span_t spans[HPU_PROGRAM_CIPHERTEXT_MULTIPLY_DMA_COUNT];
    unsigned count;
    int rc;
    if (program == FHE_PROGRAM_KEYSWITCH) {
        count = fhe_generated_keyswitch_spans(spans);
        if (count != HPU_PROGRAM_KEYSWITCH_DMA_COUNT) return 423;
        rc = hpu_program_keyswitch(spans, count);
    } else if (program == FHE_PROGRAM_RELIN) {
        count = fhe_generated_relin_spans(spans);
        if (count != HPU_PROGRAM_RELINEARIZATION_DMA_COUNT) return 424;
        rc = hpu_program_relinearization(spans, count);
    } else {
        count = fhe_generated_ciphertext_spans(spans);
        if (count != HPU_PROGRAM_CIPHERTEXT_MULTIPLY_DMA_COUNT) return 425;
        rc = hpu_program_ciphertext_multiply(spans, count);
    }
    if (rc == 0) rc = fhe_wait_terminal_sync();
    return rc;
#else
    int rc = fhe_dload(4U, FHE_LINE_MOD_CTX, 1U, 1);
    if (rc == 0 && program == FHE_PROGRAM_CIPHERTEXT_MUL) {
        rc = fhe_issue_ciphertext_prefix();
    }
    if (rc == 0) rc = fhe_issue_keyswitch(program);
    if (rc == 0) hpu_pfree(4U);
    if (rc == 0) {
        /* The entire composite program has exactly one, terminal PSYNC. */
        hpu_psync();
        rc = fhe_wait_terminal_sync();
    }
    return rc;
#endif
}
#endif

static int fhe_verify_results(fhe_program_kind program) {
    unsigned line;
    fhe_cache_invalidate((uintptr_t)fhe_memory(),
                         (size_t)HPU_IT_MEM_LINES * FHE_LINE_BYTES);
    for (line = 0U; line < HPU_IT_MEM_LINES; ++line) {
        volatile uint32_t *actual = fhe_memory_line(line);
        unsigned word;
        for (word = 0U; word < FHE_WORDS_PER_LINE; ++word) {
            uint32_t expected;
            const char *scope;
            if (line >= FHE_LINE_SCRATCH &&
                line < FHE_LINE_SCRATCH + FHE_P_COUNT * FHE_POLY_LINES) {
                unsigned source =
                    (line - FHE_LINE_SCRATCH) / FHE_POLY_LINES;
                unsigned coefficient =
                    ((line - FHE_LINE_SCRATCH) % FHE_POLY_LINES) *
                        FHE_WORDS_PER_LINE + word;
                uint32_t modulus = fhe_moduli[FHE_Q_COUNT + source];
                const uint32_t *coefficient_poly = fhe_master_line(
                    fhe_acc_line(FHE_LINE_KS_COEFF, 1U,
                                 FHE_Q_COUNT + source));
                expected = fhe_mul(
                    coefficient_poly[coefficient],
                    fhe_broadcast_values[
                        source == 0U ? 12U : (source == 1U ? 17U : 22U)],
                    modulus);
                scope = "scratch";
            } else if (line >= FHE_LINE_CIPHER_OUT &&
                       line < FHE_LINE_CIPHER_OUT +
                                  2U * FHE_Q_COUNT * FHE_POLY_LINES) {
                unsigned poly =
                    (line - FHE_LINE_CIPHER_OUT) / FHE_POLY_LINES;
                unsigned component = poly / FHE_Q_COUNT;
                unsigned basis = poly % FHE_Q_COUNT;
                unsigned coefficient =
                    ((line - FHE_LINE_CIPHER_OUT) % FHE_POLY_LINES) *
                        FHE_WORDS_PER_LINE + word;
                unsigned expected_line =
                    program == FHE_PROGRAM_KEYSWITCH && component == 1U ?
                        fhe_output_line(FHE_LINE_KS_MODDOWN, component,
                                        basis) :
                        fhe_output_line(FHE_LINE_CIPHER_OUT, component,
                                        basis);
                expected = fhe_master_line(expected_line)[coefficient];
                scope = "output";
            } else if (line < FHE_MASTER_LINES) {
                expected = fhe_master_line(line)[word];
                scope = "master_or_checkpoint";
            } else if (line < FHE_BROADCAST_END) {
                unsigned constant =
                    (line - FHE_MASTER_LINES) / FHE_BROADCAST_STRIDE;
                expected = fhe_broadcast_values[constant];
                scope = "broadcast";
            } else {
                expected = FHE_GUARD_WORD;
                scope = "guard";
            }
            if (actual[word] != expected) {
                printf("HPU_IT_FHE_MISMATCH phase=hpu-full-window "
                       "scope=%s line=%u word=%u actual=0x%x "
                       "expected=0x%x\n",
                       scope, line, word, actual[word], expected);
                return 419;
            }
        }
    }
    return 0;
}

int hpu_fhe_run(uint32_t seed, hpu_case_kind kind,
                uint64_t *cpu_compute_cycles,
                uint64_t *hpu_compute_cycles,
                uint64_t *cpu_e2e_cycles,
                uint64_t *hpu_e2e_cycles) {
    fhe_program_kind program;
    const char *name;
    const char *baseline_status;
    uint64_t before;
    uint64_t after;
#if !defined(__riscv)
    uint64_t cpu_e2e_before;
#else
    uint64_t hpu_e2e_before;
#endif
    int rc;
    (void)seed;

    if (kind == HPU_CASE_CMB_KEYSWITCH ||
        kind == HPU_CASE_PERF_KEYSWITCH) {
        program = FHE_PROGRAM_KEYSWITCH;
        name = "KeySwitch_N4096_Q4_P3_D2";
    } else if (kind == HPU_CASE_CMB_RELINE ||
               kind == HPU_CASE_PERF_RELIN) {
        program = FHE_PROGRAM_RELIN;
        name = "RelinOnly_N4096_Q4_P3_D2";
    } else if (kind == HPU_CASE_PERF_CIPHERTEXT_MUL ||
               kind == HPU_CASE_APP_MINI_FHE) {
        program = FHE_PROGRAM_CIPHERTEXT_MUL;
        name = kind == HPU_CASE_APP_MINI_FHE
            ? "MiniFHE_EncryptMultiplyRelinearizeDecrypt_N4096_Q4_P3_D2"
            : "CiphertextMultiply_N4096_Q4_P3_D2";
    } else if (kind == HPU_CASE_CMB_HMUL) {
        program = FHE_PROGRAM_CIPHERTEXT_MUL;
        name = "CMultFull_N4096_Q4_P3_D2";
    } else {
        return 420;
    }
    baseline_status = (kind == HPU_CASE_PERF_KEYSWITCH ||
                       kind == HPU_CASE_PERF_CIPHERTEXT_MUL ||
                       kind == HPU_CASE_PERF_RELIN) ?
                          "EXTERNAL_PERFORMANCE_PLAN" : "NOT_APPLICABLE";

#if defined(__riscv)
    /* Functional target cases issue the HPU program without first spending
     * minutes on a CPU oracle.  Performance cases request one algorithm-only
     * CPU baseline, followed by a lightweight eight-polynomial final check. */
    rc = fhe_validate_broadcast_math();
    if (rc != 0) return rc;
    if (cpu_compute_cycles != NULL || cpu_e2e_cycles != NULL) {
        fhe_cpu_validate_checkpoints = 0;
        before = fhe_cycle_now();
        rc = fhe_cpu_oracle(program);
        after = fhe_cycle_now();
        fhe_cpu_validate_checkpoints = 1;
        if (cpu_compute_cycles != NULL) {
            *cpu_compute_cycles = after - before;
        }
        if (cpu_e2e_cycles != NULL) {
            *cpu_e2e_cycles = after - before;
        }
        if (rc != 0) return rc;
        fhe_cpu_sink ^= fhe_final[0][seed & 3U][seed & (FHE_N - 1U)];
        rc = fhe_verify_cpu_final(program);
        if (rc != 0) return rc;
    } else {
        if (cpu_compute_cycles != NULL) *cpu_compute_cycles = 0U;
        if (cpu_e2e_cycles != NULL) *cpu_e2e_cycles = 0U;
    }

    hpu_e2e_before = fhe_cycle_now();
    rc = fhe_prepare_fixture(program);
    if (rc != 0) return rc;
    before = fhe_cycle_now();
    rc = fhe_issue_program(program);
    after = fhe_cycle_now();
    if (hpu_compute_cycles != NULL) {
        *hpu_compute_cycles = after - before;
    }
    if (hpu_e2e_cycles != NULL) {
        *hpu_e2e_cycles = after - hpu_e2e_before;
    }
    if (rc != 0) return rc;
#else
    cpu_e2e_before = fhe_cycle_now();
    rc = fhe_prepare_fixture(program);
    if (rc != 0) return rc;
    fhe_cpu_validate_checkpoints = 0;
    before = fhe_cycle_now();
    rc = fhe_cpu_oracle(program);
    after = fhe_cycle_now();
    fhe_cpu_validate_checkpoints = 1;
    if (cpu_compute_cycles != NULL) {
        *cpu_compute_cycles = after - before;
    }
    if (cpu_e2e_cycles != NULL) {
        *cpu_e2e_cycles = after - cpu_e2e_before;
    }
    if (rc != 0) return rc;
    fhe_cpu_sink ^= fhe_final[0][seed & 3U][seed & (FHE_N - 1U)];
    rc = fhe_verify_cpu_final(program);
    if (rc != 0) return rc;

    /* Host asset self-check retains every intermediate checkpoint. */
    rc = fhe_cpu_oracle(program);
    if (rc != 0) return rc;
    if (hpu_compute_cycles != NULL) *hpu_compute_cycles = 0U;
    if (hpu_e2e_cycles != NULL) *hpu_e2e_cycles = 0U;
#endif

    rc = fhe_verify_results(program);
    if (rc == 0) {
        printf("HPU_IT_FHE workload=%s master_lines=%u broadcast_lines=%u "
               "scratch_lines=%u guard_lines=%u window_lines=%u "
               "checkpoints=word_exact "
               "target_execution=%s psync=%u "
               "compute_cpu_boundary=algorithm_only "
               "compute_hpu_boundary=issue_through_terminal_sync "
               "baseline_status=%s "
               "cpu_e2e_boundary=%s hpu_e2e_boundary=%s "
               "e2e_boundary_status=UNFROZEN validation_excluded=1\n",
               name, FHE_MASTER_LINES,
               FHE_BROADCAST_COUNT * FHE_BROADCAST_STRIDE,
               FHE_SCRATCH_LINES,
               HPU_IT_MEM_LINES - FHE_GUARD_BEGIN,
               HPU_IT_MEM_LINES,
#if defined(__riscv)
               "issued", 1U, baseline_status, "algorithm_only",
               "fixture_plus_issue_through_terminal_sync");
#else
               "host_model_only", 0U, baseline_status,
               "fixture_plus_algorithm",
               "not_executed");
#endif
    }
    return rc;
}
